module.exports = [
"[project]/src/components/Header.jsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/Header.jsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/Header.jsx <module evaluation>", "default");
}),
"[project]/src/components/Header.jsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/Header.jsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/Header.jsx", "default");
}),
"[project]/src/components/Header.jsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$Header$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/Header.jsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$Header$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/Header.jsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$Header$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/components/Footer.jsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/Footer.jsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/Footer.jsx <module evaluation>", "default");
}),
"[project]/src/components/Footer.jsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/Footer.jsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/Footer.jsx", "default");
}),
"[project]/src/components/Footer.jsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$Footer$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/Footer.jsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$Footer$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/Footer.jsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$Footer$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/lib/cms.js [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "STATIC_LANDING_SLUGS",
    ()=>STATIC_LANDING_SLUGS,
    "buildCmsMetadata",
    ()=>buildCmsMetadata,
    "buildLandingPageMetadata",
    ()=>buildLandingPageMetadata,
    "getCmsBreadcrumbs",
    ()=>getCmsBreadcrumbs,
    "getCmsMarqueeServices",
    ()=>getCmsMarqueeServices,
    "getCmsSchema",
    ()=>getCmsSchema,
    "getFactoryCmsLandingPage",
    ()=>getFactoryCmsLandingPage,
    "getFactoryCmsLandingPageLive",
    ()=>getFactoryCmsLandingPageLive,
    "getFactoryCmsStaticPage",
    ()=>getFactoryCmsStaticPage,
    "getFactoryCmsStaticPageFresh",
    ()=>getFactoryCmsStaticPageFresh,
    "isPublishedCmsLandingPage",
    ()=>isPublishedCmsLandingPage,
    "normalizeCmsBodyHtml",
    ()=>normalizeCmsBodyHtml
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react.js [app-rsc] (ecmascript)");
;
const CMS_BASE_URL = process.env.NEXT_PUBLIC_CRM_CMS_BASE_URL || process.env.CRM_CMS_BASE_URL || "https://internal.lawfinity.in";
// Server fetch cache (ISR/metadata). Override via CMS_REVALIDATE_SECONDS env if needed.
const CMS_REVALIDATE_SECONDS = Number(process.env.CMS_REVALIDATE_SECONDS || 60);
// Marquee discovery is expensive — cache longer than per-page CMS (matches ISR default).
const MARQUEE_REVALIDATE_SECONDS = Number(process.env.CMS_MARQUEE_REVALIDATE_SECONDS || 300);
const MARQUEE_BFS_BATCH_SIZE = 6;
const CMS_FETCH_TIMEOUT_MS = Number(process.env.CMS_FETCH_TIMEOUT_MS || 15000);
async function fetchCms(path, { fresh = false, revalidate = CMS_REVALIDATE_SECONDS } = {}) {
    try {
        const controller = new AbortController();
        const timeoutId = setTimeout(()=>controller.abort(), CMS_FETCH_TIMEOUT_MS);
        const res = await fetch(`${CMS_BASE_URL}${path}`, {
            ...fresh ? {
                cache: "no-store"
            } : {
                next: {
                    revalidate
                }
            },
            signal: controller.signal
        });
        clearTimeout(timeoutId);
        if (!res.ok) return null;
        const data = await res.json();
        return data?.success ? data.page : null;
    } catch (error) {
        const message = String(error?.message || error || "");
        const isDynamicUsage = error?.digest === "DYNAMIC_SERVER_USAGE" || message.includes("Dynamic server usage");
        if (!isDynamicUsage && error?.name !== "AbortError") {
            console.error("[factory CMS] fetch failed:", path, error);
        }
        // Timeout is non-fatal — page shell renders and client sync fetches fresh CRM data.
        if (error?.name === "AbortError" && ("TURBOPACK compile-time value", "development") === "development") {
            console.warn("[factory CMS] fetch timeout (static fallback):", path);
        }
        return null;
    }
}
const getFactoryCmsLandingPage = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cache"])(async (slug)=>{
    return fetchCms(`/api/public/factorylicence/landing-pages/${slug}`);
});
const getFactoryCmsLandingPageLive = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cache"])(async (slug)=>{
    return fetchCms(`/api/public/factorylicence/landing-pages/${slug}`, {
        fresh: true
    });
});
const getFactoryCmsStaticPage = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cache"])(async (pageKey)=>{
    return fetchCms(`/api/public/factorylicence/static-pages/${pageKey}`);
});
async function getFactoryCmsStaticPageFresh(pageKey) {
    return fetchCms(`/api/public/factorylicence/static-pages/${pageKey}`, {
        fresh: true
    });
}
function normalizeCmsKeywords(keywords) {
    if (Array.isArray(keywords)) return keywords.filter(Boolean);
    if (typeof keywords === "string" && keywords.trim()) {
        return keywords.split(",").map((item)=>item.trim()).filter(Boolean);
    }
    return keywords;
}
function firstNonEmpty(...values) {
    return values.find((value)=>typeof value === "string" ? value.trim() : value);
}
function isTruthyCmsFlag(value) {
    if (typeof value === "string") return [
        "true",
        "1",
        "yes"
    ].includes(value.toLowerCase());
    return value === true || value === 1;
}
function isFalseyCmsFlag(value) {
    if (typeof value === "string") return [
        "false",
        "0",
        "no"
    ].includes(value.toLowerCase());
    return value === false || value === 0;
}
function parseCmsRobots(seo = {}, fallbackRobots = {}) {
    const robots = seo.robots;
    const robotsText = typeof robots === "string" ? robots.toLowerCase() : String(seo.robotsTag || seo.metaRobots || "").toLowerCase();
    const noIndex = isTruthyCmsFlag(seo.noIndex) || isTruthyCmsFlag(robots?.noIndex) || isFalseyCmsFlag(robots?.index) || robotsText.includes("noindex");
    const noFollow = isTruthyCmsFlag(seo.noFollow) || isTruthyCmsFlag(robots?.noFollow) || isFalseyCmsFlag(robots?.follow) || robotsText.includes("nofollow");
    return {
        index: noIndex ? false : fallbackRobots.index ?? true,
        follow: noFollow ? false : fallbackRobots.follow ?? true
    };
}
function buildCmsMetadata(page, fallback = {}) {
    if (!page) return fallback;
    const seo = page.seo || {};
    const canonical = firstNonEmpty(seo.canonicalUrl, seo.canonical, page.canonicalUrl, page.canonical, fallback.alternates?.canonical);
    const keywords = normalizeCmsKeywords(seo.keywords) || fallback.keywords;
    const title = firstNonEmpty(seo.title, seo.metaTitle, page.metaTitle, page.title, fallback.title);
    const description = firstNonEmpty(seo.description, seo.metaDescription, page.metaDescription, fallback.description);
    return {
        ...fallback,
        title,
        description,
        keywords,
        openGraph: {
            ...fallback.openGraph || {},
            title: firstNonEmpty(seo.ogTitle, seo.title, title, fallback.openGraph?.title),
            description: firstNonEmpty(seo.ogDescription, seo.description, description, fallback.openGraph?.description),
            url: canonical || fallback.openGraph?.url,
            images: seo.ogImage ? [
                {
                    url: seo.ogImage,
                    alt: seo.ogImageAlt || page.title || ""
                }
            ] : fallback.openGraph?.images
        },
        alternates: {
            ...fallback.alternates || {},
            canonical
        },
        robots: parseCmsRobots(seo, fallback.robots)
    };
}
async function buildLandingPageMetadata(slug, fallback = {}) {
    const page = await getFactoryCmsLandingPageLive(slug);
    return buildCmsMetadata(page, fallback);
}
function getCmsSchema(page) {
    const raw = page?.seo?.schema;
    if (!raw) return null;
    if (typeof raw === "object") return raw;
    if (typeof raw !== "string") return null;
    const trimmed = raw.trim();
    if (!trimmed) return null;
    try {
        return JSON.parse(trimmed);
    } catch (error) {
        // CMS sometimes appends duplicate trailing fragments after valid JSON-LD.
        const posMatch = String(error?.message || "").match(/position (\d+)/);
        if (posMatch) {
            try {
                return JSON.parse(trimmed.slice(0, Number(posMatch[1])).trim());
            } catch  {
                return null;
            }
        }
        return null;
    }
}
// CRM rich text sometimes ships <mark> highlights / inline background-color from
// pasted content — strip those so published pages don't show stray highlighting.
function stripCmsBodyHighlightArtifacts(html = "") {
    return String(html || "").replace(/<\/?mark\b[^>]*>/gi, "").replace(/\sstyle=(["'])((?:(?!\1).)*background-color\s*:[^"']*)((?:(?!\1).)*)\1/gi, (_match, quote, before, after)=>{
        const nextStyle = `${before}${after}`.replace(/background-color\s*:\s*[^;]+;?/gi, "").replace(/;;+/g, ";").trim();
        return nextStyle ? ` style=${quote}${nextStyle}${quote}` : "";
    });
}
// Promote bare <td> header cells to <th> for the CMS's first table row (CRM authors
// tables without explicit header markup).
function promoteCmsBodyTableHeaderCells(html = "") {
    return String(html || "").replace(/<table\b[\s\S]*?<\/table>/gi, (table)=>{
        if (/<th\b/i.test(table)) return table;
        return table.replace(/<tr\b[^>]*>[\s\S]*?<\/tr>/i, (firstRow)=>firstRow.replace(/<\/?td\b/gi, (tag)=>tag.replace(/td/i, "th")));
    });
}
function stripCmsBodyTags(value = "") {
    return String(value).replace(/<[^>]*>/g, "").replace(/\s+/g, " ").trim().toLowerCase();
}
function normalizeCmsBodyHtml(html = "") {
    let paragraphFingerprints = new Set();
    return promoteCmsBodyTableHeaderCells(stripCmsBodyHighlightArtifacts(html)).replace(/<h[1-6]\b[\s\S]*?<\/h[1-6]>|<p\b[\s\S]*?<\/p>/gi, (node)=>{
        if (/^<h[1-6]\b/i.test(node)) {
            paragraphFingerprints = new Set();
            return node;
        }
        const fingerprint = stripCmsBodyTags(node);
        if (fingerprint && paragraphFingerprints.has(fingerprint)) return "";
        if (fingerprint) paragraphFingerprints.add(fingerprint);
        return node;
    });
}
function getCmsBreadcrumbs(page) {
    const crumbs = page?.content?.breadcrumbs || page?.breadcrumbs;
    if (!Array.isArray(crumbs)) return [];
    const items = crumbs.map((item)=>({
            label: String(item?.label || item?.text || item?.name || "").replace(/<[^>]*>/g, "").trim(),
            href: item?.href || item?.link || item?.url || ""
        })).filter((item)=>item.label);
    // The current page is never a link — matches appendBreadcrumbCrumb's isLast
    // check in FactoryCmsDomSync and every hardcoded breadcrumbItems array, which
    // omit href on the last entry.
    if (items.length) items[items.length - 1] = {
        label: items[items.length - 1].label
    };
    return items;
}
const STATIC_LANDING_SLUGS = new Set([
    "factory-licence-in-delhi",
    "factory-licence-in-haryana",
    "factory-licence-in-uttar-pradesh",
    "fire-noc-in-delhi",
    "fire-noc-in-haryana",
    "fire-noc-in-uttar-pradesh",
    "pollution-noc-in-delhi",
    "pollution-noc-in-haryana",
    "pollution-noc-in-uttar-pradesh"
]);
// Static CMS pages that can seed marquee discovery (home marqueeServiceSlugs, connectedServices, etc.).
const MARQUEE_STATIC_PAGE_KEYS = [
    "home",
    "about",
    "contact",
    "blogs"
];
// Default BFS seeds when CRM list API is unavailable — entry points for each service cluster.
// New CMS pages appear in marquee when linked via connectedServices from any discovered page.
const DEFAULT_MARQUEE_DISCOVERY_SEEDS = [
    "hazardous-waste-registration",
    "biomedical-waste-management-registration",
    "hospital-registration",
    "clinical-establishment-registration"
];
// Routes that are never CMS-only service landing pages in the footer marquee.
const RESERVED_MARQUEE_SLUGS = new Set([
    ...STATIC_LANDING_SLUGS,
    "about",
    "contact",
    "blogs",
    "privacy-policy",
    "terms-conditions",
    "refund-cancellation",
    "payments",
    "api"
]);
async function fetchCmsPayload(path, { revalidate = CMS_REVALIDATE_SECONDS } = {}) {
    try {
        const controller = new AbortController();
        const timeoutId = setTimeout(()=>controller.abort(), CMS_FETCH_TIMEOUT_MS);
        const res = await fetch(`${CMS_BASE_URL}${path}`, {
            next: {
                revalidate
            },
            signal: controller.signal
        });
        clearTimeout(timeoutId);
        if (!res.ok) return null;
        const contentType = res.headers.get("content-type") || "";
        if (!contentType.includes("application/json")) return null;
        return await res.json();
    } catch  {
        return null;
    }
}
function extractSlugFromHref(href = "") {
    const value = String(href || "").trim();
    if (!value) return "";
    try {
        if (/^https?:\/\//i.test(value)) {
            const pathname = new URL(value).pathname.replace(/^\/+|\/+$/g, "");
            return pathname.split("/").filter(Boolean)[0] || "";
        }
    } catch  {
        return "";
    }
    return value.replace(/^\/+|\/+$/g, "").split("/").filter(Boolean)[0] || "";
}
function isPublishedCmsLandingPage(page) {
    if (!page?.slug) return false;
    const website = String(page.website || "factorylicence.in").toLowerCase();
    if (!website.includes("factorylicence.in")) return false;
    const status = String(page.status || "published").toLowerCase();
    if ([
        "draft",
        "archived",
        "deleted",
        "inactive"
    ].includes(status)) return false;
    const explicitlyPublished = [
        "published",
        "publish",
        "active",
        "visible"
    ].includes(status);
    const liveOnCrm = status === "needs_review" && Boolean(page.publishedAt);
    return explicitlyPublished || liveOnCrm;
}
// CMS page title for marquee pills (admin "Page Title" field — not hero/mainHeading).
function marqueeTitleFromPage(page) {
    return page?.title || page?.mainHeading || page?.content?.mainHeading || page?.content?.hero?.headline || page?.seo?.title || page?.slug;
}
function toMarqueeItem(slug, title) {
    const clean = String(slug || "").replace(/^\/+|\/+$/g, "");
    if (!clean) return null;
    return {
        slug: clean,
        title: String(title || clean).trim() || clean,
        href: `/${clean}`
    };
}
function extractMarqueeItemsFromConfig(items = []) {
    if (!Array.isArray(items)) return [];
    return items.map((item)=>{
        const slug = item?.slug || extractSlugFromHref(item?.url || item?.link || item?.href || "");
        // connectedServices uses `name`; CMS list items may use title/label.
        const title = item?.title || item?.name || item?.label || item?.mainHeading;
        return toMarqueeItem(slug, title);
    }).filter(Boolean);
}
function isMarqueeCandidateSlug(slug) {
    const clean = String(slug || "").replace(/^\/+|\/+$/g, "");
    if (!clean || RESERVED_MARQUEE_SLUGS.has(clean)) return false;
    if (clean.startsWith("blogs")) return false;
    return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(clean);
}
function enqueueMarqueeSlug(queue, slug) {
    const clean = String(slug || "").replace(/^\/+|\/+$/g, "");
    if (isMarqueeCandidateSlug(clean)) queue.push(clean);
}
// Scan CMS JSON for internal service links (connectedServices, body HTML hrefs, slug fields).
function collectInternalSlugsFromValue(value, slugs) {
    if (value == null) return;
    if (typeof value === "string") {
        const patterns = [
            /factorylicence\.in\/([a-z0-9]+(?:-[a-z0-9]+)*)/gi,
            /href=["']\/([a-z0-9]+(?:-[a-z0-9]+)*)/gi
        ];
        for (const pattern of patterns){
            let match = pattern.exec(value);
            while(match){
                if (isMarqueeCandidateSlug(match[1])) slugs.add(match[1]);
                match = pattern.exec(value);
            }
        }
        return;
    }
    if (Array.isArray(value)) {
        value.forEach((item)=>collectInternalSlugsFromValue(item, slugs));
        return;
    }
    if (typeof value === "object") {
        if (isMarqueeCandidateSlug(value.slug)) slugs.add(value.slug);
        const fromHref = extractSlugFromHref(value.url || value.link || value.href || "");
        if (isMarqueeCandidateSlug(fromHref)) slugs.add(fromHref);
        Object.values(value).forEach((item)=>collectInternalSlugsFromValue(item, slugs));
    }
}
function extractLinkedSlugsFromCmsPage(page) {
    const slugs = new Set();
    // connectedServices is how SEO links new CMS service pages — seed marquee discovery.
    collectInternalSlugsFromValue(page?.content?.connectedServices || page?.connectedServices, slugs);
    collectInternalSlugsFromValue(page?.content, slugs);
    collectInternalSlugsFromValue(page?.customSections, slugs);
    collectInternalSlugsFromValue(page?.content?.customSections, slugs);
    return Array.from(slugs);
}
function extractMarqueeSeedsFromStaticContent(content = {}) {
    const seeds = [];
    extractMarqueeItemsFromConfig(content.connectedServices).forEach((item)=>{
        seeds.push(item.slug);
    });
    extractMarqueeItemsFromConfig(content.marqueeServices || content.serviceMarquee || content.newServices || content.services || (Array.isArray(content.marqueeServiceSlugs) ? content.marqueeServiceSlugs.map((slug)=>({
            slug
        })) : [])).forEach((item)=>{
        seeds.push(item.slug);
    });
    const slugSet = new Set();
    collectInternalSlugsFromValue(content, slugSet);
    slugSet.forEach((slug)=>seeds.push(slug));
    return seeds;
}
function pagesFromListPayload(data) {
    if (!data?.success) return null;
    const pages = data.pages || data.landingPages || data.data?.pages || (Array.isArray(data.data) ? data.data : null);
    return Array.isArray(pages) && pages.length ? pages : null;
}
// CRM list endpoint (preferred) — probe all candidate paths in parallel (list API often 404).
async function fetchCmsLandingPagesList() {
    const paths = [
        `/api/public/factorylicence/published-landing-pages?website=factorylicence.in`,
        `/api/public/factorylicence/landing-pages/list?website=factorylicence.in`,
        `/api/public/factorylicence/landing-pages?website=factorylicence.in&status=published`
    ];
    const results = await Promise.all(paths.map((path)=>fetchCmsPayload(path, {
            revalidate: MARQUEE_REVALIDATE_SECONDS
        })));
    for (const data of results){
        const pages = pagesFromListPayload(data);
        if (pages) return pages;
    }
    return null;
}
// Optional CMS static pages — SEO can curate service links until CRM list API ships.
const MARQUEE_LIST_STATIC_KEYS = [
    "services-marquee",
    "service-pages",
    "marquee-services",
    "all-services"
];
async function fetchMarqueeServicesFromStaticPage(pageKey) {
    const page = await getFactoryCmsStaticPage(pageKey);
    if (!page) return [];
    const content = page.content || page.sections || {};
    const collections = [
        content.services,
        content.marqueeServices,
        content.serviceMarquee,
        content.newServices
    ].filter(Array.isArray);
    return collections.flatMap(extractMarqueeItemsFromConfig);
}
async function fetchMarqueeServicesFromStaticPages() {
    const batches = await Promise.all(MARQUEE_LIST_STATIC_KEYS.map((pageKey)=>fetchMarqueeServicesFromStaticPage(pageKey)));
    return batches.flat();
}
// Pull connectedServices / internal links from a landing page without blocking BFS on one slug.
async function harvestMarqueeLinksFromLanding(slug) {
    const page = await fetchCms(`/api/public/factorylicence/landing-pages/${slug}`, {
        revalidate: MARQUEE_REVALIDATE_SECONDS
    });
    return extractLinkedSlugsFromCmsPage(page || {});
}
// Walk CMS links from static + landing pages to discover CMS-only service pages.
async function discoverMarqueeServicesViaGraph(staticMarqueeItems = []) {
    const found = new Map();
    const visited = new Set();
    const queue = [];
    const envSeeds = String(process.env.CMS_MARQUEE_SEED_SLUGS || "").split(",").map((slug)=>slug.trim()).filter(Boolean);
    const discoverySeeds = envSeeds.length > 0 ? envSeeds : DEFAULT_MARQUEE_DISCOVERY_SEEDS;
    // Phase 1 — harvest seed slugs in parallel (was 15+ sequential CRM round-trips).
    const seedHarvests = await Promise.all([
        ...MARQUEE_STATIC_PAGE_KEYS.map(async (pageKey)=>{
            const page = await getFactoryCmsStaticPage(pageKey);
            const content = page?.content || page?.sections || {};
            return extractMarqueeSeedsFromStaticContent(content);
        }),
        // Static state landings are excluded from marquee output — only harvest their outbound links.
        ...[
            ...STATIC_LANDING_SLUGS
        ].map((slug)=>harvestMarqueeLinksFromLanding(slug))
    ]);
    for (const slugs of seedHarvests){
        for (const slug of slugs)enqueueMarqueeSlug(queue, slug);
    }
    discoverySeeds.forEach((slug)=>enqueueMarqueeSlug(queue, slug));
    for (const item of staticMarqueeItems)enqueueMarqueeSlug(queue, item.slug);
    // Phase 2 — BFS in parallel batches instead of one slug per round-trip.
    while(queue.length){
        const batch = [];
        while(batch.length < MARQUEE_BFS_BATCH_SIZE && queue.length){
            const slug = queue.shift();
            if (!slug || visited.has(slug)) continue;
            visited.add(slug);
            batch.push(slug);
        }
        if (!batch.length) break;
        const pages = await Promise.all(batch.map((slug)=>fetchCms(`/api/public/factorylicence/landing-pages/${slug}`, {
                revalidate: MARQUEE_REVALIDATE_SECONDS
            })));
        for(let i = 0; i < batch.length; i++){
            const slug = batch[i];
            const page = pages[i];
            if (!isPublishedCmsLandingPage(page)) continue;
            if (!STATIC_LANDING_SLUGS.has(slug)) {
                found.set(slug, toMarqueeItem(slug, marqueeTitleFromPage(page)));
            }
            for (const nextSlug of extractLinkedSlugsFromCmsPage(page)){
                enqueueMarqueeSlug(queue, nextSlug);
            }
        }
    }
    return Array.from(found.values());
}
const getCmsMarqueeServices = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cache"])(async ()=>{
    const items = new Map();
    const [list, staticItems] = await Promise.all([
        fetchCmsLandingPagesList(),
        fetchMarqueeServicesFromStaticPages()
    ]);
    if (list) {
        for (const page of list){
            if (!page?.slug || STATIC_LANDING_SLUGS.has(page.slug)) continue;
            if (!isPublishedCmsLandingPage(page)) continue;
            items.set(page.slug, toMarqueeItem(page.slug, marqueeTitleFromPage(page)));
        }
    }
    for (const item of staticItems){
        if (!STATIC_LANDING_SLUGS.has(item.slug)) items.set(item.slug, item);
    }
    for (const item of (await discoverMarqueeServicesViaGraph(staticItems))){
        if (!STATIC_LANDING_SLUGS.has(item.slug)) items.set(item.slug, item);
    }
    return Array.from(items.values()).sort((a, b)=>a.title.localeCompare(b.title));
});
}),
"[project]/src/components/ServiceMarqueeClient.jsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/ServiceMarqueeClient.jsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/ServiceMarqueeClient.jsx <module evaluation>", "default");
}),
"[project]/src/components/ServiceMarqueeClient.jsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/ServiceMarqueeClient.jsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/ServiceMarqueeClient.jsx", "default");
}),
"[project]/src/components/ServiceMarqueeClient.jsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$ServiceMarqueeClient$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/ServiceMarqueeClient.jsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$ServiceMarqueeClient$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/ServiceMarqueeClient.jsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$ServiceMarqueeClient$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/components/ServicePagesMarquee.jsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>ServicePagesMarquee
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$app$2d$dir$2f$link$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/client/app-dir/link.react-server.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$cms$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/cms.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$ServiceMarqueeClient$2e$jsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/ServiceMarqueeClient.jsx [app-rsc] (ecmascript)");
;
;
;
;
async function ServicePagesMarquee() {
    const services = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$cms$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getCmsMarqueeServices"])();
    if (!services.length) return null;
    // Repeat enough times so wide viewports never show a gap during the scroll loop.
    const repeatsPerHalf = Math.max(1, Math.ceil(6 / services.length));
    const oneHalf = Array.from({
        length: repeatsPerHalf
    }, ()=>services).flat();
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
        "aria-label": "Explore our services",
        className: "border-y border-[#7A3EF2]/20 bg-gradient-to-r from-[#f9f5ff] via-white to-[#f9f5ff] py-8 md:py-10",
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
            className: "max-w-7xl mx-auto px-4",
            children: [
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h2", {
                    className: "text-2xl md:text-3xl font-semibold text-[#7A3EF2] mb-5 md:mb-6 text-center",
                    children: "Our More Services"
                }, void 0, false, {
                    fileName: "[project]/src/components/ServicePagesMarquee.jsx",
                    lineNumber: 20,
                    columnNumber: 9
                }, this),
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$ServiceMarqueeClient$2e$jsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
                    services: oneHalf
                }, void 0, false, {
                    fileName: "[project]/src/components/ServicePagesMarquee.jsx",
                    lineNumber: 24,
                    columnNumber: 9
                }, this)
            ]
        }, void 0, true, {
            fileName: "[project]/src/components/ServicePagesMarquee.jsx",
            lineNumber: 19,
            columnNumber: 7
        }, this)
    }, void 0, false, {
        fileName: "[project]/src/components/ServicePagesMarquee.jsx",
        lineNumber: 15,
        columnNumber: 5
    }, this);
}
}),
"[project]/src/components/FloatingGetStartedButton.jsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/FloatingGetStartedButton.jsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/FloatingGetStartedButton.jsx <module evaluation>", "default");
}),
"[project]/src/components/FloatingGetStartedButton.jsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/FloatingGetStartedButton.jsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/FloatingGetStartedButton.jsx", "default");
}),
"[project]/src/components/FloatingGetStartedButton.jsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$FloatingGetStartedButton$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/FloatingGetStartedButton.jsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$FloatingGetStartedButton$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/FloatingGetStartedButton.jsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$FloatingGetStartedButton$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[next]/internal/font/google/poppins_81a4efb6.module.css [app-rsc] (css module)", ((__turbopack_context__) => {

__turbopack_context__.v({
  "className": "poppins_81a4efb6-module__k7ac6a__className",
  "variable": "poppins_81a4efb6-module__k7ac6a__variable",
});
}),
"[next]/internal/font/google/poppins_81a4efb6.js [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$poppins_81a4efb6$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__ = __turbopack_context__.i("[next]/internal/font/google/poppins_81a4efb6.module.css [app-rsc] (css module)");
;
const fontData = {
    className: __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$poppins_81a4efb6$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].className,
    style: {
        fontFamily: "'Poppins', 'Poppins Fallback'",
        fontStyle: "normal"
    }
};
if (__TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$poppins_81a4efb6$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].variable != null) {
    fontData.variable = __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$poppins_81a4efb6$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].variable;
}
const __TURBOPACK__default__export__ = fontData;
}),
"[project]/src/components/TrackingScript.jsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/TrackingScript.jsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/TrackingScript.jsx <module evaluation>", "default");
}),
"[project]/src/components/TrackingScript.jsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/TrackingScript.jsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/TrackingScript.jsx", "default");
}),
"[project]/src/components/TrackingScript.jsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$TrackingScript$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/TrackingScript.jsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$TrackingScript$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/TrackingScript.jsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$TrackingScript$2e$jsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/lib/blogs.js [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "fetchPublishedBlogs",
    ()=>fetchPublishedBlogs,
    "getBlogBySlug",
    ()=>getBlogBySlug,
    "getBlogRobots",
    ()=>getBlogRobots,
    "getBlogSchema",
    ()=>getBlogSchema,
    "getRelatedBlogsForServicePage",
    ()=>getRelatedBlogsForServicePage
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react.js [app-rsc] (ecmascript)");
;
const API_BASE = "https://internal.lawfinity.in";
function tryParseJsonLd(value = "") {
    const trimmed = String(value).trim();
    if (!trimmed) return null;
    try {
        return JSON.parse(trimmed);
    } catch (error) {
        // CRM sometimes appends duplicate trailing fragments after valid JSON-LD.
        const posMatch = String(error?.message || "").match(/position (\d+)/);
        if (posMatch) {
            try {
                return JSON.parse(trimmed.slice(0, Number(posMatch[1])).trim());
            } catch  {
                return null;
            }
        }
        return null;
    }
}
function getBlogSchema(blog) {
    const raw = blog?.schemaMarkup;
    if (!raw) return null;
    if (typeof raw === "object") return raw;
    let value = String(raw).trim();
    if (!value) return null;
    // SEO may paste the full <script type="application/ld+json"> block from CRM.
    value = value.replace(/^<script[^>]*>/i, "").replace(/<\/script>\s*$/i, "").trim();
    const parsed = tryParseJsonLd(value);
    if (parsed) return parsed;
    // Some CRM exports wrap JSON as an escaped string: "\"{...}\""
    if (value.startsWith('"') || value.startsWith("'")) {
        try {
            const unquoted = JSON.parse(value);
            if (typeof unquoted === "string") return tryParseJsonLd(unquoted);
            if (typeof unquoted === "object" && unquoted) return unquoted;
        } catch  {
            return null;
        }
    }
    return null;
}
function getBlogRobots(blog) {
    const robotsText = String(blog?.robots || "").toLowerCase();
    return {
        index: !(blog?.noIndex || robotsText.includes("noindex")),
        follow: !(blog?.noFollow || robotsText.includes("nofollow"))
    };
}
const fetchPublishedBlogs = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cache"])(async ()=>{
    const res = await fetch(`${API_BASE}/api/public/published-fl?limit=1000`, {
        cache: "no-store"
    });
    if (!res.ok) return null;
    const data = await res.json();
    return Array.isArray(data?.blogs) ? data.blogs : [];
});
// CRM stores blogs for multiple websites in one shared database. The single-blog-by-slug
// endpoint below is not site-scoped (unlike published-fl), so we must verify ownership
// ourselves before rendering a blog on this site.
const SITE_WEBSITE_NAME = "Factory Licence";
function belongsToThisSite(blog) {
    return String(blog?.websiteName || "").toLowerCase() === SITE_WEBSITE_NAME.toLowerCase();
}
const RELATED_BLOG_LIMIT = 3;
const BLOG_HIDDEN_STATUSES = new Set([
    "draft",
    "hidden",
    "archived",
    "deleted",
    "inactive",
    "pending"
]);
const STOP_WORDS = new Set([
    "and",
    "the",
    "for",
    "with",
    "from",
    "your",
    "you",
    "our",
    "are",
    "this",
    "that",
    "into",
    "about",
    "page",
    "service",
    "services",
    "online",
    "apply",
    "process",
    "guide",
    "complete",
    "latest",
    "new",
    "in"
]);
const SERVICE_GROUPS = [
    {
        key: "factory",
        terms: [
            "factory licence",
            "factory license",
            "factory registration",
            "mcd factory",
            "manufacturing"
        ]
    },
    {
        key: "fire",
        terms: [
            "fire noc",
            "fire safety",
            "fire certificate",
            "dfs",
            "fire"
        ]
    },
    {
        key: "pollution",
        terms: [
            "pollution noc",
            "pollution certificate",
            "pollution control",
            "cte",
            "cto",
            "pcb"
        ]
    }
];
const LOCATION_TERMS = [
    "delhi",
    "haryana",
    "uttar pradesh",
    "up",
    "noida",
    "ghaziabad",
    "meerut",
    "rewari",
    "sonipat"
];
function plainText(value) {
    if (Array.isArray(value)) return value.map(plainText).join(" ");
    if (value && typeof value === "object") return Object.values(value).map(plainText).join(" ");
    return String(value || "").replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
}
function firstPresent(...values) {
    return values.map(plainText).find(Boolean) || "";
}
function truncateText(value, maxLength = 150) {
    const text = plainText(value);
    if (text.length <= maxLength) return text;
    const trimmed = text.slice(0, maxLength).trim();
    const lastSpace = trimmed.lastIndexOf(" ");
    return `${trimmed.slice(0, lastSpace > 80 ? lastSpace : trimmed.length)}...`;
}
function normalizeBlogSlug(blog) {
    return String(blog?.urlSlug || blog?.slug || "").replace(/^\/?blogs\//, "").replace(/^\/+/, "").replace(/\/+$/, "");
}
function slugToTitle(slug) {
    return String(slug || "").split("-").filter(Boolean).map((word)=>word.charAt(0).toUpperCase() + word.slice(1)).join(" ");
}
function tokenize(value) {
    return plainText(value).toLowerCase().replace(/[^a-z0-9\s]/g, " ").split(/\s+/).filter((word)=>word.length > 2 && !STOP_WORDS.has(word));
}
function findMatchingGroups(value) {
    const text = plainText(value).toLowerCase();
    return SERVICE_GROUPS.filter((group)=>group.terms.some((term)=>text.includes(term))).map((group)=>group.key);
}
function findLocations(value) {
    const text = plainText(value).toLowerCase();
    return LOCATION_TERMS.filter((term)=>text.includes(term));
}
function getBlogSearchText(blog) {
    return plainText([
        normalizeBlogSlug(blog),
        blog?.title,
        blog?.metaTitle,
        blog?.category,
        blog?.excerpt,
        blog?.metaDescription,
        blog?.description,
        blog?.tags,
        blog?.keywords
    ]);
}
function getPageSearchText(page, slug) {
    return plainText([
        slug,
        page?.title,
        page?.mainHeading,
        page?.heading,
        page?.metaTitle,
        page?.metaDescription,
        page?.description,
        page?.serviceCategory,
        page?.category,
        page?.keywords,
        page?.tags,
        page?.seo?.title,
        page?.seo?.description,
        page?.content?.title,
        page?.content?.heading,
        page?.content?.description,
        page?.content?.hero?.headline,
        page?.content?.hero?.subtext,
        page?.sections?.hero?.title,
        page?.sections?.hero?.description
    ]);
}
function isSearchablePublishedBlog(blog) {
    const slug = normalizeBlogSlug(blog);
    if (!slug) return false;
    const status = String(blog?.status || "").toLowerCase();
    if (BLOG_HIDDEN_STATUSES.has(status)) return false;
    if (blog?.noIndex || blog?.noFollow) return false;
    const robots = String(blog?.robots || "").toLowerCase();
    return !robots.includes("noindex") && !robots.includes("nofollow");
}
function buildRelatedBlogContext(page, slug) {
    const text = getPageSearchText(page, slug);
    return {
        tokens: [
            ...new Set(tokenize(text))
        ],
        groups: findMatchingGroups(text),
        locations: findLocations(text)
    };
}
function scoreRelatedBlog(blog, context) {
    const searchText = getBlogSearchText(blog).toLowerCase();
    const titleText = plainText([
        normalizeBlogSlug(blog),
        blog?.title,
        blog?.metaTitle
    ]).toLowerCase();
    let score = 0;
    context.groups.forEach((group)=>{
        const terms = SERVICE_GROUPS.find((item)=>item.key === group)?.terms || [];
        if (terms.some((term)=>searchText.includes(term))) score += 20;
    });
    context.locations.forEach((location)=>{
        if (searchText.includes(location)) score += 10;
    });
    context.tokens.forEach((token)=>{
        if (titleText.includes(token)) score += 2;
        else if (searchText.includes(token)) score += 1;
    });
    return score;
}
function getBlogDateValue(blog) {
    return Date.parse(blog?.publishedAt || blog?.updatedAt || blog?.createdAt || "") || 0;
}
function toRelatedBlogCard(blog) {
    const slug = normalizeBlogSlug(blog);
    return {
        slug,
        title: firstPresent(blog?.title, blog?.metaTitle, slugToTitle(slug)),
        excerpt: truncateText(firstPresent(blog?.excerpt, blog?.metaDescription, blog?.description, blog?.content)),
        category: firstPresent(blog?.category),
        publishedAt: blog?.publishedAt || blog?.updatedAt || blog?.createdAt || null
    };
}
const getRelatedBlogsForServicePage = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cache"])(async (page, slug, limit = RELATED_BLOG_LIMIT)=>{
    const blogs = await fetchPublishedBlogs();
    if (!Array.isArray(blogs)) return [];
    const context = buildRelatedBlogContext(page, slug);
    return blogs.filter(isSearchablePublishedBlog).map((blog)=>({
            blog,
            score: scoreRelatedBlog(blog, context)
        })).filter(({ score })=>score > 0).sort((a, b)=>b.score - a.score || getBlogDateValue(b.blog) - getBlogDateValue(a.blog)).slice(0, limit).map(({ blog })=>toRelatedBlogCard(blog));
});
const getBlogBySlug = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cache"])(async (slug)=>{
    if (!slug) return null;
    try {
        const res = await fetch(`${API_BASE}/api/public/blog/${encodeURIComponent(slug)}`, {
            cache: "no-store"
        });
        if (res.ok) {
            const blog = await res.json();
            // Reject blogs that belong to another website (e.g. Lawfinity) even though the
            // slug matched in the shared CRM database.
            if (blog && !blog.error && belongsToThisSite(blog)) return blog;
        }
    } catch  {
    // Fall back to list snapshot below.
    }
    const blogs = await fetchPublishedBlogs();
    if (!blogs) return null;
    return blogs.find((blog)=>blog?.urlSlug === slug) || null;
});
}),
"[project]/src/app/layout.js [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>RootLayout,
    "metadata",
    ()=>metadata
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/headers.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$Header$2e$jsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/Header.jsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$Footer$2e$jsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/Footer.jsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$ServicePagesMarquee$2e$jsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/ServicePagesMarquee.jsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$script$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/script.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$FloatingGetStartedButton$2e$jsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/FloatingGetStartedButton.jsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$poppins_81a4efb6$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[next]/internal/font/google/poppins_81a4efb6.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$TrackingScript$2e$jsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/TrackingScript.jsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$blogs$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/blogs.js [app-rsc] (ecmascript)");
;
;
;
;
;
;
;
;
;
;
;
;
const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://factorylicence.in").replace(/\/+$/, "");
const metadata = {
    metadataBase: new URL(SITE_URL),
    title: "Factory Licence Registration & Renewal Online in India | Apply Now",
    description: "Apply factory license online in India with expert Factory License Consultant support. Get factory licence registration, renewal online, fees, certificate & process help.",
    keywords: "factory license, factory licence, factory license renewal, factory license registration, factory license renewal online, factory license fees, Factory Licence Renewal, factory registration certificate, factory act licence, mcd factory licence, factory licence online, factory licence registration, apply factory license, apply for factory license, factory licence apply online, factory licence online, factory licence renewal fees, factory licence renewal fees online payment, factory licence renewal online, factory registration online, online factory licence, online factory licence renewal, online registration of factory licence, renewal of factory license online, factory licence fees, factory licence online application, Online Factory Registration in India, Factory License Consultant, factory license application, factory registration process, factory act license, factory licence certificate, factory licence mcd, factory license for construction site, licence factory, license for factory, mcd licence for factory, mcd license for factory, online factory license, how to pay factory license fee online, how to renew factory license online, how to apply for factory license",
    alternates: {
        canonical: "https://factorylicence.in/"
    },
    robots: {
        index: true,
        follow: true
    }
};
async function RootLayout({ children }) {
    const headersList = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["headers"])();
    const pathname = headersList.get("x-pathname") || "";
    const blogSlugMatch = pathname.match(/^\/blogs\/([^/]+)\/?$/);
    // Blog articles with CRM schemaMarkup — render in <head> (body scripts get corrupted by RSC).
    let showSiteSchema = true;
    let blogSchemaJson = null;
    if (blogSlugMatch) {
        const blog = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$blogs$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getBlogBySlug"])(blogSlugMatch[1]);
        const schema = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$blogs$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getBlogSchema"])(blog);
        if (schema) {
            showSiteSchema = false;
            blogSchemaJson = JSON.stringify(schema).replace(/</g, "\\u003c");
        }
    }
    const schemaData = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "ProfessionalService",
                "@id": "https://factorylicence.in/#organization",
                name: "Factory Licence",
                url: "https://factorylicence.in/",
                telephone: "+91 99107 74687",
                address: {
                    "@type": "PostalAddress",
                    streetAddress: "T-10, Pankaj Plaza, Pocket 7, Sector 12 Dwarka",
                    addressLocality: "Dwarka, New Delhi",
                    addressRegion: "Delhi",
                    postalCode: "110078",
                    addressCountry: "IN"
                },
                sameAs: [
                    "https://www.facebook.com/factorylicence",
                    "https://www.instagram.com/factorylicence.in/",
                    "https://www.linkedin.com/company/factorylicence/",
                    "https://www.youtube.com/@FactoryLicence"
                ],
                openingHoursSpecification: [
                    {
                        "@type": "OpeningHoursSpecification",
                        dayOfWeek: [
                            "Monday",
                            "Tuesday",
                            "Wednesday",
                            "Thursday",
                            "Friday",
                            "Saturday"
                        ],
                        opens: "10:00",
                        closes: "19:00"
                    }
                ],
                areaServed: "IN",
                contactPoint: {
                    "@type": "ContactPoint",
                    contactType: "customer support",
                    telephone: "+91 99107 74687",
                    areaServed: [
                        "IN"
                    ],
                    availableLanguage: [
                        "en",
                        "hi"
                    ]
                }
            },
            {
                "@type": "WebSite",
                "@id": "https://factorylicence.in/#website",
                url: "https://factorylicence.in/",
                name: "Factory Licence",
                publisher: {
                    "@id": "https://factorylicence.in/#organization"
                }
            }
        ]
    };
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("html", {
        lang: "en",
        suppressHydrationWarning: true,
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("head", {
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("script", {
                        dangerouslySetInnerHTML: {
                            __html: `(function(){var e=console.error;var msg="Unable to store cookie";console.error=function(){var a=arguments[0];var s=typeof a==="string"?a:(a&&a.message||"");if(s&&s.indexOf(msg)!==-1)return;return e.apply(console,arguments);};})();`
                        }
                    }, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 121,
                        columnNumber: 9
                    }, this),
                    blogSchemaJson ? /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("script", {
                        id: "blog-schema-org",
                        type: "application/ld+json",
                        dangerouslySetInnerHTML: {
                            __html: blogSchemaJson
                        }
                    }, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 128,
                        columnNumber: 11
                    }, this) : null,
                    showSiteSchema ? /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("script", {
                        id: "schema-org",
                        type: "application/ld+json",
                        dangerouslySetInnerHTML: {
                            __html: JSON.stringify(schemaData)
                        }
                    }, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 136,
                        columnNumber: 11
                    }, this) : null,
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$script$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
                        id: "gtm-script",
                        strategy: "lazyOnload",
                        children: `
            (function(w,d){
              function loadGtm(){
                if (d.getElementById('gtm-runtime')) return;
                w.dataLayer=w.dataLayer||[];
                w.dataLayer.push({'gtm.start':new Date().getTime(),event:'gtm.js'});
                var f=d.getElementsByTagName('script')[0];
                var j=d.createElement('script');
                j.id='gtm-runtime';
                j.async=true;
                j.src='https://www.googletagmanager.com/gtm.js?id=GTM-TR58JL6Q';
                f.parentNode.insertBefore(j,f);
              }
              w.setTimeout(loadGtm,4500);
            })(window,document);
          `
                    }, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 144,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$script$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
                        id: "meta-pixel",
                        strategy: "lazyOnload",
                        children: `
            (function(w,d){
              function loadMeta(){
                if(w.fbq)return;
                var n=w.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                if(!w._fbq)w._fbq=n;
                n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];
                var t=d.createElement('script');
                t.async=!0;
                t.src='https://connect.facebook.net/en_US/fbevents.js';
                var s=d.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(t,s);
                n('init','777415601527541');
                n('track','PageView');
              }
              w.setTimeout(loadMeta,5000);
            })(window,document);
          `
                    }, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 164,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/src/app/layout.js",
                lineNumber: 116,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("body", {
                className: `${__TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$poppins_81a4efb6$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"].variable} font-sans`,
                suppressHydrationWarning: true,
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("script", {
                        dangerouslySetInnerHTML: {
                            __html: `
(function(){
  var attrs = ['fdprocessedid','data-lt-installed','form_signature','alternative_form_signature','field_signature','visibility_annotation'];
  function strip(){
    try {
      attrs.forEach(function(attr){
        document.querySelectorAll('['+attr+']').forEach(function(el){ el.removeAttribute(attr); });
      });
    } catch(e){}
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', strip);
  else strip();
  try {
    var obs = new MutationObserver(strip);
    obs.observe(document.documentElement, { attributes: true, subtree: true, attributeFilter: attrs });
  } catch(e){}
})();
            `.trim()
                        }
                    }, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 187,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$TrackingScript$2e$jsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {}, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 209,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$FloatingGetStartedButton$2e$jsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {}, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 211,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("noscript", {
                        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("iframe", {
                            src: "https://www.googletagmanager.com/ns.html?id=GTM-TR58JL6Q",
                            height: "0",
                            width: "0",
                            style: {
                                display: "none",
                                visibility: "hidden"
                            }
                        }, void 0, false, {
                            fileName: "[project]/src/app/layout.js",
                            lineNumber: 214,
                            columnNumber: 11
                        }, this)
                    }, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 213,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("noscript", {
                        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("img", {
                            height: "1",
                            width: "1",
                            style: {
                                display: "none"
                            },
                            src: "https://www.facebook.com/tr?id=777415601527541&ev=PageView&noscript=1",
                            alt: ""
                        }, void 0, false, {
                            fileName: "[project]/src/app/layout.js",
                            lineNumber: 223,
                            columnNumber: 11
                        }, this)
                    }, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 222,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$Header$2e$jsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {}, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 232,
                        columnNumber: 9
                    }, this),
                    children,
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["Suspense"], {
                        fallback: null,
                        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$ServicePagesMarquee$2e$jsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {}, void 0, false, {
                            fileName: "[project]/src/app/layout.js",
                            lineNumber: 236,
                            columnNumber: 11
                        }, this)
                    }, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 235,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$Footer$2e$jsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {}, void 0, false, {
                        fileName: "[project]/src/app/layout.js",
                        lineNumber: 238,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/src/app/layout.js",
                lineNumber: 185,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/src/app/layout.js",
        lineNumber: 115,
        columnNumber: 5
    }, this);
}
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__b39d6ea7._.js.map